#!/usr/bin/env python3
"""
generate_svgs.py — Individual SVG Label File Generator
======================================================

Reads the generated labels CSV and produces one SVG file per label,
each sized to the exact card dimensions (86mm × 54mm). These SVGs
can be opened directly in xTool Creative Space (XCS) for engraving.

  INPUT:
    output/labels_batch.csv    — Generated by generate_labels.py

  OUTPUT:
    output/svg/001_Variety_Name.svg
    output/svg/002_Variety_Name.svg
    ... (one file per label row)

  LAYOUT:
    ┌──────────────────────────────────────┐
    │        << Variety Name >>             │  ← Bold, 4.5mm
    │            (Type)                     │  ← Italic, 3.2mm
    │ ──────────────────────────────────── │  ← Separator line
    │          Bloom: ______               │  ← Regular, 2.8mm
    │         Harvest: ______              │
    │       Fertility: ______              │
    │            Use: ______               │
    │          Origin: ______              │
    │ ──────────────────────────────────── │  ← Separator line
    │         Planted: 2026                │  ← Bold, 2.8mm
    │  Planted by: Peter Brown & ...       │  ← Regular, 2.5mm
    └──────────────────────────────────────┘

Usage:
    python3 data/generate_svgs.py

Dependencies:
    Python 3.6+ (stdlib only — csv, os, re, html)

Note:
    Run generate_labels.py FIRST to create/update labels_batch.csv.
"""

import csv
import os
import re
import html

# ══════════════════════════════════════════════════════════════════════
# USE FIELD ABBREVIATION
# ══════════════════════════════════════════════════════════════════════
# Some varieties have very long Use fields (e.g., "Cooking/Sauce;
# Eating Fresh; Espalier; Pies; Sweet Cider" = 56 chars). At 2.8mm
# font size, the card width (80mm usable) can hold ~45 characters.
# Fields exceeding MAX_USE_LEN are automatically shortened using
# the abbreviation map below.
# ══════════════════════════════════════════════════════════════════════

# Maximum characters for Use field before abbreviating
MAX_USE_LEN = 45

# Abbreviation map for common Use terms (only applied when field is too long)
USE_ABBREV = {
    "Cooking/Sauce": "Cook",
    "Eating Fresh": "Fresh",
    "Sweet Cider": "Cider",
    "Hard Cider": "Hard Cider",  # Already short enough — keep as-is
}


def shorten_use(use_str):
    """
    Abbreviate the Use field if it exceeds MAX_USE_LEN characters.

    Splits on semicolons, replaces known long terms with abbreviations,
    and rejoins. Only applies abbreviations when the original string
    is too long — short Use fields pass through unchanged.

    Args:
        use_str: Original Use field value (e.g., "Cooking/Sauce; Eating Fresh; Pies")

    Returns:
        Shortened string if over limit, otherwise original string
    """
    if len(use_str) <= MAX_USE_LEN:
        return use_str
    parts = [p.strip() for p in use_str.split(";")]
    shortened = [USE_ABBREV.get(p, p) for p in parts]
    result = "; ".join(shortened)
    return result


# ══════════════════════════════════════════════════════════════════════
# CARD DIMENSIONS AND LAYOUT
# ══════════════════════════════════════════════════════════════════════
# All measurements are in millimeters. The SVG viewBox maps 1 unit = 1mm.
# xTool Black Metal Business Cards are 86mm × 54mm (standard CR80).
# ══════════════════════════════════════════════════════════════════════

# Card dimensions in mm
CARD_W = 86
CARD_H = 54
MARGIN = 3  # mm inset from card edge (safe zone for engraving)

# Font sizes in mm (SVG uses viewBox units = mm)
FONT_NAME = 4.5     # Variety name — large and bold for easy identification
FONT_TYPE = 3.2     # Fruit type — italic, slightly smaller
FONT_DETAIL = 2.8   # Bloom, Harvest, Fertility, Use, Origin fields
FONT_FOOTER = 2.5   # Footer text — smallest, least prominent

# Vertical positions (Y coordinate in mm from top of card)
# These control the spacing between each line of text.
# Adjust these values to rebalance the layout if adding/removing fields.
LAYOUT = {
    "name":      7,      # Variety name (top section)
    "type":     12.5,    # Fruit type (below name)
    # --- separator line at y=15 ---
    "bloom":    19,      # Bloom period
    "harvest":  24,      # Harvest period
    "fertility": 29,     # Pollination/fertility info
    "use":      34,      # Primary uses
    "origin":   39,      # Geographic origin and year
    # --- separator line at y=42 ---
    "year":     46,      # Year planted (bottom section)
    "footer":   51,      # Planted by line
}

# Horizontal positioning — all text is centered on the card
LEFT = MARGIN
CENTER_X = CARD_W / 2


def sanitize_filename(name):
    """
    Create a filesystem-safe filename from a variety name.

    Removes special characters (apostrophes, trademark symbols, etc.)
    and replaces spaces with underscores.

    Args:
        name: Variety name (e.g., "Peter's Honey Fig")

    Returns:
        Safe filename string (e.g., "Peters_Honey_Fig")
    """
    s = re.sub(r'[^\w\s-]', '', name)
    s = re.sub(r'\s+', '_', s.strip())
    return s


def escape(text):
    """
    Escape text for safe inclusion in SVG XML.

    Converts characters like &, <, >, " to their XML entity equivalents
    (e.g., & becomes &amp;). Required because SVG is XML-based.

    Args:
        text: Raw text string

    Returns:
        XML-safe escaped string
    """
    return html.escape(str(text), quote=True)


def generate_svg(row, index):
    """
    Generate the complete SVG markup for one label card.

    The SVG uses millimeter units with a viewBox matching the card size,
    so 1 SVG unit = 1mm on the physical card. All text uses text-anchor
    "middle" for center alignment.

    Args:
        row: Dict with label fields (Name, Type, Bloom_Period, etc.)
        index: Label number (1-based, used for debugging only)

    Returns:
        Complete SVG XML string ready to write to a file
    """
    # Extract all fields from the label row
    name = row.get("Name", "")
    tree_type = row.get("Type", "")
    bloom = row.get("Bloom_Period", "")
    harvest = row.get("Harvest_Period", "")
    fertility = row.get("Fertility", "")
    use = shorten_use(row.get("Use", ""))  # Auto-abbreviate if too long
    origin = row.get("Origin", "")
    year = row.get("Year_Planted", "")
    footer = row.get("Footer", "")

    # Build the SVG XML string using an f-string template.
    # The viewBox "0 0 86 54" means coordinates map directly to mm.
    # The light gray rectangle is a visual boundary guide (not engraved).
    svg = f'''<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg"
     width="{CARD_W}mm" height="{CARD_H}mm"
     viewBox="0 0 {CARD_W} {CARD_H}">

  <!-- Card boundary — light gray outline for alignment reference only.
       This rectangle is NOT engraved (stroke is too thin and gray). -->
  <rect x="0" y="0" width="{CARD_W}" height="{CARD_H}"
        fill="none" stroke="#cccccc" stroke-width="0.1" />

  <!-- Variety Name (large, centered) -->
  <text x="{CENTER_X}" y="{LAYOUT['name']}"
        font-family="Arial, Helvetica, sans-serif"
        font-size="{FONT_NAME}" font-weight="bold"
        text-anchor="middle" fill="black">{escape(name)}</text>

  <!-- Type (centered, below name) -->
  <text x="{CENTER_X}" y="{LAYOUT['type']}"
        font-family="Arial, Helvetica, sans-serif"
        font-size="{FONT_TYPE}" font-style="italic"
        text-anchor="middle" fill="black">{escape(tree_type)}</text>

  <!-- Separator line -->
  <line x1="{MARGIN}" y1="15" x2="{CARD_W - MARGIN}" y2="15"
        stroke="black" stroke-width="0.2" />

  <!-- Detail fields (centered) -->
  <text x="{CENTER_X}" y="{LAYOUT['bloom']}"
        font-family="Arial, Helvetica, sans-serif"
        font-size="{FONT_DETAIL}" text-anchor="middle" fill="black">Bloom: {escape(bloom)}</text>

  <text x="{CENTER_X}" y="{LAYOUT['harvest']}"
        font-family="Arial, Helvetica, sans-serif"
        font-size="{FONT_DETAIL}" text-anchor="middle" fill="black">Harvest: {escape(harvest)}</text>

  <text x="{CENTER_X}" y="{LAYOUT['fertility']}"
        font-family="Arial, Helvetica, sans-serif"
        font-size="{FONT_DETAIL}" text-anchor="middle" fill="black">Fertility: {escape(fertility)}</text>

  <text x="{CENTER_X}" y="{LAYOUT['use']}"
        font-family="Arial, Helvetica, sans-serif"
        font-size="{FONT_DETAIL}" text-anchor="middle" fill="black">Use: {escape(use)}</text>

  <text x="{CENTER_X}" y="{LAYOUT['origin']}"
        font-family="Arial, Helvetica, sans-serif"
        font-size="{FONT_DETAIL}" text-anchor="middle" fill="black">Origin: {escape(origin)}</text>

  <!-- Separator line -->
  <line x1="{MARGIN}" y1="42" x2="{CARD_W - MARGIN}" y2="42"
        stroke="black" stroke-width="0.2" />

  <!-- Year Planted (centered) -->
  <text x="{CENTER_X}" y="{LAYOUT['year']}"
        font-family="Arial, Helvetica, sans-serif"
        font-size="{FONT_DETAIL}" font-weight="bold"
        text-anchor="middle" fill="black">Planted: {escape(year)}</text>

  <!-- Footer (centered) -->
  <text x="{CENTER_X}" y="{LAYOUT['footer']}"
        font-family="Arial, Helvetica, sans-serif"
        font-size="{FONT_FOOTER}"
        text-anchor="middle" fill="black">{escape(footer)}</text>

</svg>'''
    return svg


def main():
    """
    Main entry point — reads labels CSV and generates one SVG per label.

    Steps:
      1. Resolve file paths relative to the project root
      2. Create output/svg/ directory if it doesn't exist
      3. Read all rows from labels_batch.csv
      4. For each row, generate an SVG and write it to a numbered file
      5. Print summary with file count and output location
    """
    # Resolve paths relative to this script's location
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_dir = os.path.dirname(script_dir)
    csv_path = os.path.join(project_dir, "output", "labels_batch.csv")
    svg_dir = os.path.join(project_dir, "output", "svg")

    # Ensure the output directory exists
    os.makedirs(svg_dir, exist_ok=True)

    # Read all label rows from the CSV (generated by generate_labels.py)
    with open(csv_path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        rows = list(reader)

    print(f"Read {len(rows)} labels from {csv_path}")

    # Generate one SVG file per label row
    for i, row in enumerate(rows, start=1):
        # Filename format: 001_Variety_Name.svg (zero-padded for sort order)
        name = row.get("Name", f"label_{i}")
        filename = f"{i:03d}_{sanitize_filename(name)}.svg"
        filepath = os.path.join(svg_dir, filename)

        svg_content = generate_svg(row, i)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(svg_content)

    print(f"Generated {len(rows)} SVG files in {svg_dir}/")
    print(f"Each file is {CARD_W}mm × {CARD_H}mm — open individually in XCS")


if __name__ == "__main__":
    main()
